apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  strategy: {}
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - args:
            - python
            - consumer.py
            - -p
            - "5672"
            - -s
            - project2-rabbitmq
          image: bennylevinger/consumer:1.0.63
          name: consumer
          resources: {}
      restartPolicy: Always

