apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  strategy: {}
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - args:
            - python
            - consumer.py
            - -p
            - "5672"
            - -s
            - rabbitmq
          image: bennylevinger/consumer:1.0.63
          name: consumer
        - args:
            - python
            - producer.py
            - -p
            - "5672"
            - -s
            - rabbitmq
            - -m
            - Hello
            - -r
            - "30"
          image: bennylevinger/producer:1.0.63
          name: producer
        - image: rabbitmq:3-management
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672  
          resources: {}
      restartPolicy: Always

      
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
status:
  loadBalancer: {}
 