apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  strategy: {}
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - args:
            - python
            - producer.py
            - -p
            - "5672"
            - -s
            - project2-rabbitmq
            - -m
            - Hello
            - -r
            - "30"
          image: bennylevinger/producer:1.0.63
          name: producer
          resources: {}
      restartPolicy: Always

